export const gamesAdmin = [
  {
    id: 1,
    status: "Pending",
    stage: 32,
    date: "2022-04-10",
    hour: "19:00",
    homeTeam: "Barcelona",
    awayTeam: "Real Madrid",
    homeTeamGoals: 0,
    awayTeamGoals: 0,
  },
  {
    id: 2,
    status: "Pending",
    stage: 32,
    date: "2022-04-15",
    hour: "20:00",
    homeTeam: "Manchester United",
    awayTeam: "Liverpool",
    homeTeamGoals: 0,
    awayTeamGoals: 0,
  },
  {
    id: 3,
    status: "Pending",
    stage: 16,
    date: "2022-04-20",
    hour: "21:00",
    homeTeam: "PSG",
    awayTeam: "Bayern Munich",
    homeTeamGoals: 0,
    awayTeamGoals: 0,
  },
];
