export const players = [
  {
    nombre: "Lionel",
    apellido: "Messi",
    equipo: "Rosario Central",
    fechaNacimiento: "24/06/1987",
    imagen: "https://example.com/messi.jpg",
  },
  {
    nombre: "Sergio",
    apellido: "Aguero",
    equipo: "Independiente",
    fechaNacimiento: "02/06/1988",
    imagen: "https://example.com/aguero.jpg",
  },
  {
    nombre: "Paulo",
    apellido: "Dybala",
    equipo: "Instituto",
    fechaNacimiento: "15/11/1993",
    imagen: "https://example.com/dybala.jpg",
  },
  {
    nombre: "Angel",
    apellido: "Di Maria",
    equipo: "Rosario Central",
    fechaNacimiento: "14/02/1988",
    imagen: "https://example.com/dimaria.jpg",
  },
  {
    nombre: "Gonzalo",
    apellido: "Higuain",
    equipo: "River Plate",
    fechaNacimiento: "10/12/1987",
    imagen: "https://example.com/higuain.jpg",
  },
  {
    nombre: "Javier",
    apellido: "Mascherano",
    equipo: "River Plate",
    fechaNacimiento: "08/06/1984",
    imagen: "https://example.com/mascherano.jpg",
  },
  {
    nombre: "Juan Roman",
    apellido: "Riquelme",
    equipo: "Boca Juniors",
    fechaNacimiento: "24/06/1978",
    imagen: "https://example.com/riquelme.jpg",
  },
  {
    nombre: "Carlos",
    apellido: "Tevez",
    equipo: "Boca Juniors",
    fechaNacimiento: "05/02/1984",
    imagen: "https://example.com/tevez.jpg",
  },
  {
    nombre: "Esteban",
    apellido: "Andrada",
    equipo: "Boca Juniors",
    fechaNacimiento: "26/07/1991",
    imagen: "https://example.com/andrada.jpg",
  },
  {
    nombre: "Nicolas",
    apellido: "Tagliafico",
    equipo: "Independiente",
    fechaNacimiento: "31/08/1992",
    imagen: "https://example.com/tagliafico.jpg",
  },
  {
    nombre: "Diego",
    apellido: "Maradona",
    equipo: "Boca Juniors",
    fechaNacimiento: "30/10/1960",
    imagen: "https://example.com/maradona.jpg",
  },
  {
    nombre: "Gabriel",
    apellido: "Batistuta",
    equipo: "River Plate",
    fechaNacimiento: "01/02/1969",
    imagen: "https://example.com/batistuta.jpg",
  },
  {
    nombre: "Juan",
    apellido: "Pablo Sorin",
    equipo: "River Plate",
    fechaNacimiento: "05/05/1976",
    imagen: "https://example.com/sorin.jpg",
  },
  {
    nombre: "Javier",
    apellido: "Zanetti",
    equipo: "Independiente",
    fechaNacimiento: "10/08/1973",
    imagen: "https://example.com/zanetti.jpg",
  },
  {
    nombre: "Hernan",
    apellido: "Crespo",
    equipo: "River Plate",
    fechaNacimiento: "05/07/1975",
    imagen: "https://example.com/crespo.jpg",
  }
];
