const stadiums = [
  {id:1,
    nombre: "Estadio Monumental Antonio Vespucio Liberti",
    equipo: "River Plate",
    provincia: "Ciudad de Buenos Aires",
    pais: "Argentina",
  },
  {id:2,
    nombre: "Estadio Alberto J. Armando",
    equipo: "Boca Juniors",
    provincia: "Ciudad de Buenos Aires",
    pais: "Argentina",
  },
  {id:3,
    nombre: "Estadio Presidente Juan Domingo Perón",
    equipo: "Racing Club",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:4,
    nombre: "Estadio Libertadores de América",
    equipo: "Independiente",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:5,
    nombre: "Estadio Tomás Adolfo Ducó",
    equipo: "Huracán",
    provincia: "Ciudad de Buenos Aires",
    pais: "Argentina",
  },
  {id:6,
    nombre: "Estadio Brigadier General Estanislao López",
    equipo: "Unión",
    provincia: "Santa Fe",
    pais: "Argentina",
  },
  {id:7,
    nombre: "Estadio Mario Alberto Kempes",
    equipo: "Instituto",
    provincia: "Córdoba",
    pais: "Argentina",
  },
  {id:8,
    nombre: "Estadio Ciudad de La Plata",
    equipo: "Estudiantes",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:9,
    nombre: "Estadio Único Madre de Ciudades",
    equipo: "Santiago del Estero",
    provincia: "Santiago del Estero",
    pais: "Argentina",
  },
  {id:10,
    nombre: "Estadio José Dellagiovanna",
    equipo: "Tigre",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:11,
    nombre: "Estadio Bicentenario Ciudad de San Juan",
    equipo: "San Martín de San Juan",
    provincia: "San Juan",
    pais: "Argentina",
  },
  {id:12,
    nombre: "Estadio Julio Humberto Grondona",
    equipo: "Arsenal",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:13,
    nombre: "Estadio Presbítero Bartolomé Grella",
    equipo: "Patronato",
    provincia: "Entre Ríos",
    pais: "Argentina",
  },
  {id:14,
    nombre: "Estadio Coloso del Parque",
    equipo: "Newell's Old Boys",
    provincia: "Santa Fe",
    pais: "Argentina",
  },
  {id:15,
    nombre: "Estadio Malvinas Argentinas",
    equipo: "Godoy Cruz",
    provincia: "Mendoza",
    pais: "Argentina",
  },
  {id:16,
    nombre: "Estadio Ciudad de Caseros",
    equipo: "Club Atlético Estudiantes",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:17,
    nombre: "Estadio Eva Perón",
    equipo: "Club Atlético Sarmiento",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:18,
    nombre: "Estadio Padre Martearena",
    equipo: "Club Atlético Juventud Antoniana",
    provincia: "Salta",
    pais: "Argentina",
  },
  {id:19,
    nombre: "Estadio José María Minella",
    equipo: "Club Atlético Aldosivi",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:20,
    nombre: "Estadio Bicentenario Ciudad de Catamarca",
    equipo: "Club Atlético San Lorenzo de Alem",
    provincia: "Catamarca",
    pais: "Argentina",
  },
  {id:21,
    nombre: "Estadio José Dellagiovanna",
    equipo: "Club Atlético Tigre",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:22,
    nombre: "Estadio Pedro Bidegain",
    equipo: "Club Atlético San Lorenzo de Almagro",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:23,
    nombre: "Estadio Presbítero Bartolomé Grella",
    equipo: "Club Atlético Patronato",
    provincia: "Entre Ríos",
    pais: "Argentina",
  },
  {id:24,
    nombre: "Estadio Centenario Dr. José Luis Meiszner",
    equipo: "Club Atlético Brown",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:25,
    nombre: "Estadio Diego Armando Maradona",
    equipo: "Argentinos Juniors",
    provincia: "Ciudad de Buenos Aires",
    pais: "Argentina",
  },
  {id:26,
    nombre: "Estadio Nuevo Monumental",
    equipo: "Deportivo Maipú",
    provincia: "Mendoza",
    pais: "Argentina",
  },
  {id:27,
    nombre: "Estadio Ciudad de Lanús - Néstor Díaz Pérez",
    equipo: "Lanús",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:28,
    nombre: "Estadio Ciudad de Vicente López",
    equipo: "Colegiales",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:29,
    nombre: "Estadio 23 de Agosto",
    equipo: "Gimnasia y Esgrima de Jujuy",
    provincia: "Jujuy",
    pais: "Argentina",
  },
  {id:30,
    nombre: "Estadio Eva Perón",
    equipo: "Sarmiento",
    provincia: "Buenos Aires",
    pais: "Argentina",
  },
  {id:31,
    nombre: "Estadio Gigante de Arroyito",
    equipo: "Rosario Central",
    provincia: "Santa Fe",
    pais: "Argentina",
  },
  {id:32,
    nombre: "Estadio Ciudad de Córdoba",
    equipo: "Belgrano",
    provincia: "Córdoba",
    pais: "Argentina",
  },
  {id:33,
    nombre: "Estadio Mario Alberto Kempes",
    equipo: "Talleres",
    provincia: "Córdoba",
    pais: "Argentina",
  },
  {id:34,
    nombre: "Estadio Presbítero Bartolomé Grella",
    equipo: "Atlético Paraná",
    provincia: "Entre Ríos",
    pais: "Argentina",
  },
];

module.exports = stadiums;